version: "3.5"

services:
  db:
    container_name: db
    image: "postgres:alpine"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gorest

  app:
    container_name: gorest
    build:
      context: .
    ports:
      - "9000:8080" # In our .env file above, we chose port 4000
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: gorest

    volumes:
      - .:/app

volumes:
  db-data:
